# Generated by Django 4.1 on 2022-10-22 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0012_rename_estado_pedido_estado_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='estado_pedido',
            new_name='estado',
        ),
    ]
